server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: sms #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://sms   #匹配后提供服务的路由地址
          predicates:
            - Path=/sms/**   #将当前请求转发到http://127.0.0.1：9001/product/1
          filters:   #配置路由过滤器，将当前请求http://127.0.0.1：9001/product-service/product/1    --》   http://127.0.0.1：9001/product/1
            - RewritePath=/sms/(?<segment>.*), /$\{segment}    #路径重写的过滤器，在yml中$写为$\断言，路径相匹配的进行路由
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**   #将当前请求转发到http://127.0.0.1：9001/product/1
          filters:   #配置路由过滤器，将当前请求http://127.0.0.1：9001/product-service/product/1    --》   http://127.0.0.1：9001/product/1
            - RewritePath=/test/(?<segment>.*), /$\{segment}    #路径重写的过滤器，在yml中$写为$\断言，路径相匹配的进行路由
