server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: sms #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://sms   #匹配后提供服务的路由地址
          predicates:
            - Path=/sms/**          #断言，路径相匹配的进行路由
        - id: sms #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          uri: lb://test   #匹配后提供服务的路由地址
          predicates:
            - Path=/sgtest/**          #断言，路径相匹配的进行路由