server:
  port: 8001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: authentication #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://authentication           #匹配后提供服务的路由地址
          predicates:
            - Path=/api/auth/**          #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=2
        - id: sms
          uri: lb://sms
          predicates:
            - Path=/api/sms/**
          filters:
            - StripPrefix=2
eureka:
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6868/eureka
